[package]
authors = [
    "Hunar Roop Kahlon <hunar.roop@gmail.com>"
]
description = "The Cymple Compiler Collection"
edition = "2018"
license = "Apache-2.0 OR MIT"
name = "ccc"
version = "0.1.0"

[dependencies.nom]
version = "5.1.0"
